import type { Metadata } from "next";
import "./globals.css";
import React_query_provider from "@/components/react-query/react-query-provider";
import TopMenu from "@/components/navBar/TopMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <React_query_provider>
          <TopMenu />
          {children}
        </React_query_provider>
      </body>
    </html>
  );
}
