import type { Metadata } from 'next';
import './globals.css';

import { dir } from 'i18next';

import TopMenu from '@/types/components/navBar/TopMenu';
import React_query_provider from '@/types/components/react-query/react-query-provider';
import ThemeProvider from '@/types/theme/ThemeProvider';

import { languages } from '../../utils/i18n/settings';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: any };
}) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
    >
      <body>
        <React_query_provider>
          <ThemeProvider>
            <TopMenu />
            {children}
          </ThemeProvider>
        </React_query_provider>
      </body>
    </html>
  );
}
