import type { Metadata } from 'next';
import './globals.css';

import { dir } from 'i18next';
import { getServerSession } from 'next-auth';

import TopMenu from '@/types/components/navBar/TopMenu';
import React_query_provider from '@/types/components/react-query/react-query-provider';
import SessionProvider from '@/types/components/session/SessionProvider';
import ThemeProvider from '@/types/theme/ThemeProvider';

import { languages } from '../../utils/i18n/settings';
import { roboto, vazirmatn } from '@/types/styles/fonts';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutProps = {
  children: React.ReactNode;
  params: { lng: string };
};
export default async function RootLayout({
  children,
  params: { lng },
}: RootLayoutProps) {
  
  const session = await getServerSession();

    return (
      <html
        lang={lng}
        dir={dir(lng)}
        className={ dir(lng) === 'rtl' ? vazirmatn.className : roboto.className }
      >
        <body>
          <React_query_provider>
            <SessionProvider session={session}>
              <ThemeProvider>
                <TopMenu />
                {children}
              </ThemeProvider>
            </SessionProvider>
          </React_query_provider>
        </body>
      </html>
    );
}
