import { RootLayoutProps, metadata } from "./layout";
import { expect } from '@jest/globals';

const rootLayoutProps: RootLayoutProps = {
  children: <>The content goes here</>,
  params: { lng: "en" },
};

describe('metadata', () => {
  it('contains the expected title', () => {
    expect(metadata.title).toBe('Create Next App');
  });

  it('contains the expected description', () => {
    expect(metadata.description).toBe('Generated by create next app');
  });

});