import './globals.css';

import { dir } from 'i18next';
import { getServerSession, Session } from 'next-auth';

import TopMenu from '@/types/components/navBar/TopMenu';
import React_query_provider from '@/types/components/react-query/react-query-provider';
import SessionProvider from '@/types/components/session/SessionProvider';
import ThemeProvider from '@/types/theme/ThemeProvider';

import { languages } from '../../utils/i18n/settings';

import type { Metadata } from 'next';
export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export type RootLayoutProps = {
  children: React.ReactNode;
  params: { lng: string; session: Session | null };
};

export async function getServerSideProps() {
  const session = await getServerSession();
  return {
    props: { session },
  };
}

export default function RootLayout({
  children,
  params: { lng, session },
}: RootLayoutProps) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
    >
      <body>
        <React_query_provider>
          <SessionProvider session={session}>
            <ThemeProvider>
              <TopMenu />
              {children}
            </ThemeProvider>
          </SessionProvider>
        </React_query_provider>
      </body>
    </html>
  );
}
